<start> ::= <rdf_instance>
<rdf_instance> ::= <footballer> | <club> | <league> | <country>
<footballer> ::= "foot:Footballer(" <id> ", " <input_string> ", " <input_string> ", " <birthday> "^^xsd:date, " <input_string> "," <array_of_strings> "," <value> "," <position_str> "," <input_string> ")" "."
<club> ::= "foot:Club(" <id> "," <input_string> "," <year> "^^xsd:gYear," <input_string> "," <input_string> "," <input_string> ")" "."
<league> ::= "foot:League(" <id> "," <leagueName> "," <year> "^^xsd:gYear," <input_string> "," <array_of_strings> "," <array_of_strings> ")" "."
<country> ::= "foot:Country(" <id> "," <countryName> "," <continent> "," <fifaCode> "," <array_of_strings> "," <array_of_strings> "," <array_of_strings> ")" "."
<id> ::= "_:" <letter_or_digit> <letter_or_digit> <letter_or_digit>
<letter_or_digit> ::= <letter> | <digit>
<letter> ::= "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j" | "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r" | "s" | "t" | "u" | "v" | "w" | "x" | "y" | "z" 
           | "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J" | "K" | "L" | "M" | "N" | "O" | "P" | "Q" | "R" | "S" | "T" | "U" | "V" | "W" | "X" | "Y" | "Z"
<digit> ::= "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"
<position_str> ::= "\"" <position> "\""
<position> ::= "Goalkeeper" | "Defender" | "Midfielder" | "Striker"
<year> ::= "\"" <digit> <digit> <digit> <digit> "\""
<continent> ::= <input_string>
<fifaCode> ::= <input_string>
<countryName> ::= <input_string>
<leagueName> ::= <input_string>
<value> ::= <digit> <digit> <digit> <digit> <digit> <digit>
<array_of_strings> ::= "(" <input_string> "," <input_string> "," <input_string> ")"
<input_string> ::= "\"" <string3> "\"" | "\"" <string4> "\"" | "\"" <string5> "\"" | "\"" <string6> "\"" | "\"" <string7> "\""
<string3> ::= <string> <string> <string>
<string4> ::= <string> <string> <string> <string>  
<string5> ::= <string> <string> <string> <string> <string>
<string6> ::= <string> <string> <string> <string> <string> <string>
<string7> ::= <string> <string> <string> <string> <string> <string> <string>
<string> ::= <letter> | <string> <letter> | <string> <digit> | <string> <otherName>
<birthday> ::= "\"" "19" <fiveToNine> <digit> "-" <month> "-" <day> "\"" | "\"" "20" <zeroToTwo> <digit> "-" <month> "-" <day> "\""
<fiveToNine> ::= "5" | "6" | "7" | "8" | "9"
<zeroToTwo> ::= "0" | "1" | "2"
<month> ::= "0" <digitFromOne> | "10" | "11" | "12"
<day> ::= "0" <digitFromOne> | "1" <digit> | "2" <digit>
<digitFromOne> ::= "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"
<otherName> ::= "_" | "-"