<start> ::= <rdf_instance>
<rdf_instance> ::= <footballer> | <club> | <league> | <country>
<footballer> ::= "foot:Footballer(" <id> ", " <input_string> ", " <input_string> ", " <birthday> "^^xsd:date, " <input_string> "," <array_of_strings> "," <value> "," <position_str> "," <input_string> ")" "." | "foot:Footballer(" <invalid_id> ", " <input_string> ", " <input_string> ", " <invalid_birthday> "^^xsd:date, " <input_string> "," <array_of_strings> "," <invalid_value> "," <invalid_position> "," <input_string> ")" "."
<club> ::= "foot:Club(" <id> "," <input_string> "," <year> "^^xsd:gYear," <input_string> "," <input_string> "," <input_string> ")" "." | "foot:Club(" <invalid_id> "," <input_string> "," <invalid_year> "^^xsd:gYear," <input_string> "," <input_string> "," <input_string> ")" "."
<league> ::= "foot:League(" <id> "," <leagueName> "," <year> "^^xsd:gYear," <input_string> "," <array_of_strings> "," <array_of_strings> ")" "." | "foot:League(" <invalid_id> "," <invalid_leagueName> "," <invalid_year> "^^xsd:gYear," <input_string> "," <array_of_strings> "," <array_of_strings> ")" "."
<country> ::= "foot:Country(" <id> "," <countryName> "," <continent> "," <fifaCode> "," <array_of_strings> "," <array_of_strings> "," <array_of_strings> ")" "." | "foot:Country(" <invalid_id> "," <invalid_countryName> "," <invalid_continent> "," <invalid_fifaCode> "," <array_of_strings> "," <array_of_strings> "," <array_of_strings> ")" "."
<id> ::= "_:" <letter_or_digit> <letter_or_digit> <letter_or_digit> | "_:" <digit> | "_:" <invalid_character> | "_:" <id_without_valid_characters>
<invalid_id> ::= "_:" <invalid_character> | "_:" <letter_or_digit> <letter_or_digit>
<invalid_birthday> ::= "\"1989-13-15""\"^^xsd:date" | "\"2000-00-00""\"^^xsd:date" 
<invalid_year> ::= "\"" "1899" "\"" | "\"" "1890"
<invalid_value> ::= "12345"
<invalid_position> ::= "\"Goalie\"" 
<invalid_leagueName> ::= "\"" "UnknownLeague" "\"" | "\"123\""  
<invalid_countryName> ::= "XY" 
<invalid_continent> ::= "!" | "@" 
<invalid_fifaCode> ::= "Z#" 
<array_of_strings> ::= "(" <input_string> "," <input_string> "," <input_string> ")" | "(" <input_string> "," <input_string> ")" | "(" <input_string> "," <invalid_input_string> "," <input_string> ")" 
<input_string> ::= "\"" <string3> "\"" | "\"" <string4> "\"" | "\"" <string5> "\"" | "\"" <string6> "\"" | "\"" <string7> "\""  | "\"" <invalid_string> "\""
<string3> ::= <string> <string> <string>
<string4> ::= <string> <string> <string> <string>
<string5> ::= <string> <string> <string> <string> <string>
<string6> ::= <string> <string> <string> <string> <string> <string>
<string7> ::= <string> <string> <string> <string> <string> <string> <string>
<invalid_string> ::= "ab!" | "12#3" | "$%&"
<birthday> ::= "\"" "19" <fiveToNine> <digit> "-" <month> "-" <day> "\"" | "\"" "20" <zeroToTwo> <digit> "-" <month> "-" <day> "\""
<fiveToNine> ::= "5" | "6" | "7" | "8" | "9"
<zeroToTwo> ::= "0" | "1" | "2"
<digit> ::= "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"
<month> ::= "01" | "02" | "03" | "04" | "05" | "06" | "07" | "08" | "09" | "10" | "11" | "12"
<day> ::= "01" | "02" | "03" | "04" | "05" | "06" | "07" | "08" | "09" | "10" | "11" | "12" | "13" | "14" | "15" | "16" | "17" | "18" | "19" | "20" | "21" | "22" | "23" | "24" | "25" | "26" | "27" | "28" | "29" | "30" | "31"
<letter_or_digit> ::= <letter>
<letter> ::= "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j" | "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r" | "s" | "t" | "u" | "v" | "w" | "x" | "y" | "z" | "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J" | "K" | "L" | "M" | "N" | "O" | "P" | "Q" | "R" | "S" | "T" | "U" | "V" | "W" | "X" | "Y" | "Z"
<otherName> ::= "_" | "-"
<value> ::= <digit> <digit> <digit> <digit> <digit> <digit> | <invalid_value>
<position_str> ::= "\"" <position> "\""
<position> ::= "Goalkeeper" | "Defender" | "Midfielder" | "Striker" | "Goalie"
<year> ::= "\"" <digit> <digit> <digit> <digit> "\""
<leagueName> ::= <input_string> | <invalid_leagueName>
<countryName> ::= <input_string> | <invalid_countryName>
<continent> ::= <input_string> | <invalid_continent>
<fifaCode> ::= <input_string> | <invalid_fifaCode>
<invalid_character> ::= "!" | "@" | "#" | "$" | "%" | "^" | "&" | "*" | "(" | ")" | "-" | "_" | "+" | "=" | "[" | "]" | "{" | "}" | "|" | ";" | ":" | "'" | "\"" | "," | "<" | ">" | "." | "?" | "/" | "\\" | "`" | "~"
<random_invalid_character> ::= "!" | "@" | "#" | "$" | "%" | "^" | "&" | "*" | "(" | ")" | "-" | "_" | "+" | "=" | "[" | "]" | "{" | "}" | "|" | ";" | ":" | "'" | "\"" | "," | "<" | ">" | "." | "?" | "/" | "\\" | "`" | "~"
<id_without_valid_characters> ::= "_:" <random_invalid_character> <random_invalid_character> <random_invalid_character>
<string> ::= <letter> | <string> <letter> | <string> <digit> | <string> <otherName>
<invalid_input_string> ::= "\"" "ab!" "\"" | "\"" "12#3" "\"" | "\"" "$%&" "\""